acromegaly:
- id: case_1
  text: |
    A 41-year-old man, Pavel Ivanov, presents with complaints of intermittent headaches and a gradual increase in shoe and ring size over the past two years. 
    His coworkers have noticed subtle facial changes, and he reports mild joint discomfort in his hands. 
    On examination, blood pressure is 138/88 mmHg, pulse 76 bpm, height 180 cm, weight 92 kg, and BMI 28.4 kg/m². 
    Laboratory evaluation reveals fasting glucose of 6.3 mmol/L and HbA1c of 6.0%. 
    He takes no regular medications. His father has hypertension, and his mother is healthy. There is no family history of endocrine disorders.
- id: case_2
  text: |
    A 36-year-old woman, Elena Sokolova, attends the clinic due to persistent fatigue, mild hand swelling, and recent dental spacing noted during a routine dental visit. 
    She denies vision problems or menstrual irregularities. Vital signs show blood pressure 124/82 mmHg, pulse 72 bpm, and BMI 26.1 kg/m². 
    Laboratory findings include fasting glucose 5.9 mmol/L and mildly elevated serum phosphate at 1.6 mmol/L. She is otherwise healthy and takes only a daily multivitamin. 
    Her mother was treated for thyroid nodules, and her father has type 2 diabetes.

wilson_disease:
- id: case_1
  text: |
    A 22-year-old man, Nikita Petrov, presents with fatigue, mild tremor of the hands, and occasional mood swings over the past six months. 
    He denies alcohol use or drug intake. Physical examination reveals mild hepatomegaly without jaundice. Vital signs are within normal limits. 
    Laboratory analysis shows serum ALT 78 U/L, AST 64 U/L, total bilirubin 1.3 mg/dL, and slightly low ceruloplasmin at 0.16 g/L. 
    Complete blood count is unremarkable. Both parents are healthy; his older sister was once noted to have elevated liver enzymes of unclear cause.
- id: case_2
  text: |
    A 19-year-old woman, Alina Kuznetsova, reports recent episodes of hand clumsiness and increased irritability. 
    She also mentions a slight yellowish tint to her eyes noticed by her mother. Vital signs are normal, with blood pressure 110/70 mmHg and pulse 74 bpm. 
    Laboratory evaluation reveals serum ALT 92 U/L, AST 85 U/L, total bilirubin 1.6 mg/dL, and low serum ceruloplasmin at 0.14 g/L. 
    Urinary copper excretion is mildly elevated. There is no family history of liver disease, and she takes no medications.

spigfd:
- id: case_1
  text: |
    A 9-year-old boy, Timur Kadyrov, is brought by his parents for evaluation of short stature. 
    He has consistently been below the 3rd percentile for height, though his weight is proportionate. He was born at term with normal birth weight. 
    On examination, height is 114 cm, weight 23 kg, BMI 17.7 kg/m². Pubertal development is Tanner stage I. 
    Laboratory evaluation reveals normal growth hormone levels but low serum IGF-1 concentration at 25 ng/mL (reference 80–350). 
    Both parents are of average height. There is no chronic illness or medication use.
- id: case_2
  text: |
    An 11-year-old girl, Daria Stepanenko, presents with poor linear growth despite good appetite and activity. 
    Her height velocity over the past year was 3 cm. She denies chronic disease or medication use. 
    Physical exam shows height 120 cm, weight 26 kg, BMI 18.0 kg/m², with no dysmorphic features. 
    Laboratory results show fasting GH 8.2 ng/mL (normal), but IGF-1 32 ng/mL (low). 
    Family history reveals no short stature; both parents are healthy.

stills_disease:
- id: case_1
  text: |
    A 28-year-old woman, Olga Mikhailova, reports intermittent high fevers for two weeks, associated with sore throat and generalized body aches. 
    She notes transient pinkish rash appearing on her trunk during febrile episodes. 
    Vital signs reveal temperature 38.7°C, pulse 96 bpm, and blood pressure 112/70 mmHg. 
    Laboratory studies show mild leukocytosis at 13.5×10⁹/L and elevated CRP of 35 mg/L. 
    She takes no regular medications. Her family history is unremarkable.
- id: case_2
  text: |
    A 15-year-old boy, Andrei Lebedev, presents with recurrent evening fevers and joint pain in his wrists and knees for the past month. 
    He reports occasional faint rash on his arms during fever spikes. Vital signs show temperature 38.2°C and pulse 90 bpm. 
    Laboratory results indicate WBC 14.2×10⁹/L, ESR 48 mm/h, and mild transaminitis. 
    His mother has rheumatoid arthritis, and his father is healthy.

fabry_disease:
- id: case_1
  text: |
    A 27-year-old man, Mikhail Romanov, presents with burning pain in his hands and feet, worse after exercise or heat exposure. 
    He also reports occasional abdominal discomfort and reduced sweating. On examination, there are small reddish macules over the lower abdomen. 
    Vital signs are normal. Serum creatinine is 1.0 mg/dL, and urinalysis shows trace protein. 
    His maternal uncle had kidney failure in his 40s.
- id: case_2
  text: |
    A 33-year-old woman, Irina Volkova, complains of episodic sharp pain in her feet and a long history of heat intolerance. 
    She notes mild hearing difficulties. Examination reveals normal vital signs and scattered angiokeratomas on her thighs. 
    Laboratory findings show serum creatinine 0.9 mg/dL and low alpha-galactosidase A activity. 
    Her mother and maternal grandfather both had similar symptoms.

hemophagocytic_lymphohistiocytosis:
- id: case_1
  text: |
    A 5-year-old boy, Sergei Morozov, is admitted with persistent fever lasting 10 days and poor appetite. 
    His parents report recent lethargy and mild abdominal distension. Temperature is 39.1°C, pulse 110 bpm, blood pressure 95/60 mmHg. 
    Physical examination reveals palpable spleen 3 cm below the costal margin. 
    Laboratory results show hemoglobin 10.4 g/dL, platelets 115×10⁹/L, WBC 3.1×10⁹/L, and elevated ferritin 980 µg/L.
- id: case_2
  text: |
    A 12-year-old girl, Viktoria Denisova, presents with fever, malaise, and mild jaundice. 
    On exam, she appears fatigued, with hepatosplenomegaly. Vital signs: temperature 38.8°C, pulse 102 bpm, blood pressure 100/68 mmHg. 
    Laboratory data show cytopenia (Hb 9.8 g/dL, platelets 90×10⁹/L), ferritin 1200 µg/L, and triglycerides 3.5 mmol/L. 
    She has no chronic illnesses, and her parents are healthy.

homocystinuria:
- id: case_1
  text: |
    A 14-year-old boy, Denis Kuznetsov, is referred for tall, slender build and myopia. 
    He has experienced two episodes of leg pain suggestive of deep vein thrombosis. Height is 176 cm, weight 50 kg, BMI 16.1 kg/m². 
    Laboratory studies reveal plasma homocysteine 95 µmol/L (elevated) and low folate levels. 
    Family history shows that a maternal uncle had an early stroke at age 35.
- id: case_2
  text: |
    A 10-year-old girl, Marina Sidorova, presents for developmental delay and vision problems. 
    She is thin and tall for her age. Ophthalmologic exam confirms lens subluxation. 
    Laboratory evaluation reveals plasma homocysteine 88 µmol/L and low vitamin B12. 
    Her parents are healthy and unrelated. There is no family history of metabolic disease.

muckle_wells_syndrome:
- id: case_1
  text: |
    A 23-year-old woman, Kristina Popova, reports recurrent episodes of urticarial rash accompanied by joint pain and low-grade fever. 
    Symptoms occur several times a month without clear triggers. On examination, there is mild erythematous rash over her arms. 
    Temperature 37.9°C, pulse 82 bpm. Laboratory tests reveal CRP 28 mg/L and ESR 40 mm/h. 
    Her mother also suffers from episodic rash and hearing loss.
- id: case_2
  text: |
    A 17-year-old boy, Alexey Fedorov, presents with intermittent rash, joint stiffness, and mild hearing difficulty. 
    Vital signs are stable. Laboratory results show elevated inflammatory markers (CRP 22 mg/L, ESR 35 mm/h). 
    His maternal grandfather reportedly had similar skin and joint symptoms. 
    There are no other significant findings.
paroxysmal_nocturnal_hemoglobinuria:
- id: case_1
  text: |
    A 34-year-old man, Sergei Belov, presents with dark-colored urine in the morning and fatigue over the past several months. 
    Physical examination is unremarkable. Vital signs: blood pressure 118/76 mmHg, pulse 80 bpm. 
    Laboratory findings show hemoglobin 10.8 g/dL, LDH 680 U/L, and low haptoglobin. 
    Urinalysis is positive for hemoglobin without red cells. He denies recent infections or medications.
- id: case_2
  text: |
    A 29-year-old woman, Yulia Antonova, reports recurrent episodes of morning urine discoloration and mild shortness of breath on exertion. 
    Examination shows pale conjunctiva but no jaundice. Blood pressure is 110/72 mmHg, pulse 78 bpm. 
    Laboratory data reveal hemoglobin 9.6 g/dL, reticulocyte count 4.5%, and elevated LDH 720 U/L. 
    No family history of hematologic disease is noted.

prader_willi_syndrome:
- id: case_1
  text: |
    A 7-year-old boy, Ilya Tarasov, is evaluated for obesity and developmental delay. 
    His parents report poor feeding in infancy followed by excessive appetite from age three. 
    He has mild hypotonia and learning difficulties. Height 118 cm, weight 34 kg, BMI 24.4 kg/m². 
    Physical exam shows small hands and almond-shaped eyes. Both parents are healthy and non-consanguineous.
- id: case_2
  text: |
    A 10-year-old girl, Sofia Lebedeva, presents with behavioral issues and progressive weight gain despite dietary supervision. 
    Her parents note short stature compared to peers. On examination, height 126 cm, weight 44 kg, BMI 27.7 kg/m². 
    She shows mild hypotonia and narrow forehead. No chronic illnesses are reported in the family.

primary_biliary_cholangitis:
- id: case_1
  text: |
    A 54-year-old woman, Tatiana Morozova, complains of persistent fatigue and pruritus for six months. 
    She denies abdominal pain or alcohol use. Vital signs are normal. 
    Laboratory results show ALP 320 U/L, GGT 210 U/L, AST 48 U/L, and normal bilirubin. 
    She takes atorvastatin 10 mg daily for hyperlipidemia. Her mother had rheumatoid arthritis.
- id: case_2
  text: |
    A 49-year-old woman, Marina Petrova, presents with generalized itching and mild right upper quadrant discomfort. 
    She denies jaundice or dark urine. Physical exam is normal. 
    Laboratory data reveal ALP 280 U/L, ALT 52 U/L, total bilirubin 0.8 mg/dL, and positive antimitochondrial antibodies. 
    She is otherwise healthy and on no medications. Both parents are alive and well.
