acromegaly:
  - id: case_1
    text: |
      A 36-year-old man, Andrei Petrov, presents with progressive enlargement of hands and feet, 
      headaches, and excessive sweating over the past two years. 
      He reports needing larger shoes and noticing coarsening of facial features. 
      No visual field defects are reported. Laboratory evaluation shows elevated IGF-1 and impaired fasting glucose. 
      On examination, he is overweight with increased head circumference. 
      Family history is notable for diabetes in his father and hypertension in his mother. 
      He was recently started on metformin for impaired glucose tolerance.
  - id: case_2
    text: |
      A 34-year-old woman, Sofia Ivanova, reports subtle facial puffiness and mild fatigue over the past year. 
      Her dentist noted increased interdental spacing, and she recently changed her ring size. She attributes her symptoms to weight gain and stress. 
      Physical examination reveals slightly thickened skin and mild frontal bossing, but no visual changes. IGF-1 is mildly elevated; 
      oral glucose tolerance test shows borderline suppression of GH.
wilson_disease:
  - id: case_1
    text: |
      Patient Andrei Ivanov, a 16‑year‑old male, presented with complaints of persistent fatigue and occasional mild abdominal discomfort over the past three months. 
      His family noted a subtle yellowing of the eyes, though he denied pruritus, dark urine, or pale stools. 
      There was no history of alcohol intake, drug use, or significant past illness. 
      Family history was negative for liver or neurological disease. On examination, 
      Andrei appeared well nourished, with mild scleral icterus. 
      The liver edge was palpable 2 cm below the right costal margin, smooth and mildly tender. 
      No splenomegaly was detected. Neurological examination revealed no tremor, dysarthria, or abnormal movements. 
      Laboratory investigations showed mildly elevated transaminases, with ALT and AST both above the upper limit of normal, 
      and a borderline increase in total bilirubin. Serum ceruloplasmin was reduced at 12 mg/dL. 
      A 24‑hour urinary copper excretion was elevated at 150 µg/24h. 
      Hematological studies showed no evidence of hemolysis. 
      Abdominal ultrasound confirmed mild hepatomegaly with preserved parenchymal echotexture. 
      Ophthalmological slit‑lamp examination revealed early Kayser–Fleischer rings at the corneal periphery.
  - id: case_2
    text: |
      A 29-year-old woman, Katerina Dmitrieva, presents with complaints of chronic, subtle tremors in her hands and mild difficulty with coordination over the past year. 
      She also reports episodes of fatigue and irritability. Her mother had a history of psychiatric illness, 
      but there was no history of liver disease. Examination shows slight dysarthria and mild rigidity in her upper extremities, though no overt tremors. 
      The liver is not palpable. Laboratory findings reveal a low serum ceruloplasmin level at 7 mg/dL, 
      and a 24-hour urinary copper excretion is markedly elevated at 400 µg/24h. Serum bilirubin is normal.

spigfd:
  - id: case_1
    text: |
      A 28-year-old woman, Mila Markova, presents with persistent low-grade fever, muscle aches, 
      and unintentional weight loss over the past three months. 
      She also reports occasional mouth ulcers and erythematous rash over her cheeks. 
      Her family history is notable for autoimmune disorders, including lupus in her maternal aunt. 
      On examination, she has a butterfly-shaped rash on her face, mild joint swelling in the hands, and a temperature of 38°C. 
      Blood work shows elevated ESR, CRP, and a positive ANA test. A skin biopsy from the rash site shows interface dermatitis. 
      Rheumatology is consulted, and lupus is considered, but further workup, including a negative anti-dsDNA, raises concern for a more rare autoimmune etiology.
  - id: case_2
    text: |
      A 24-year-old man, Dmitry Fedorov, presents with a recent onset of recurrent fevers, 
      headache, and myalgias, accompanied by an increasing joint pain in his knees. 
      He reports no recent travel but notes a recent increase in skin rashes on his forearms. 
      Family history includes a mother with rheumatoid arthritis. 
      On examination, he has low-grade fever, tender joints, and a maculopapular rash along his forearms. 
      Lab tests reveal mildly elevated inflammatory markers (ESR, CRP), negative rheumatoid factor, and a mild leukocytosis. 
      A recent joint X-ray shows soft tissue swelling but no erosions. 
      A skin biopsy from his rash shows features concerning for a rare systemic inflammatory disease.
stills_disease:
  - id: case_1
    text: |
      A 32-year-old woman, Yulia Tarasova, presents with intermittent high fevers, sore throat, and muscle aches over the past two months. 
      She denies recent infections, but has noticed a rash that appears on her arms and legs during fever episodes. She has a family history of autoimmunity, 
      including rheumatoid arthritis in her mother. On examination, she has a temperature of 39.5°C, mild hepatomegaly, 
      and a salmon-colored maculopapular rash on her upper arms. Blood tests reveal mild leukocytosis, elevated liver enzymes (ALT, AST), 
      and an ESR of 90 mm/hr. Her ferritin level is elevated at 3000 ng/mL.
  - id: case_2
    text: |
      A 26-year-old man, Ivan Sokolov, reports recurring episodes of high fever, sore throat, 
      and a diffuse rash over the past four months. He also has weight loss and persistent fatigue. 
      His family history is negative for autoimmune disease. On examination, he has a fever of 40°C, 
      mild hepatomegaly, and a non-pruritic salmon-colored rash on his torso and limbs. Lab results show elevated ferritin (2800 ng/mL), 
      mild liver dysfunction (elevated ALT), and an ESR of 80 mm/hr. A biopsy of his skin rash shows nonspecific inflammation.
fabry_disease:
  - id: case_1
    text: |
      A 25-year-old man, Nikolai Petrov, presents with episodes of severe burning pain in his hands and feet over the past 18 months. 
      He also reports progressive hearing loss and corneal opacities. His family history is significant for a maternal uncle who died of kidney failure at age 45. 
      On examination, Nikolai has bilateral corneal opacities and decreased hearing in both ears. 
      Sensory testing reveals diminished sensation to pain and temperature in the hands and feet. 
      Urinary tests show elevated albumin and protein. A skin biopsy shows deposits consistent with glycosphingolipids. 

  - id: case_2
    text: |
      A 29-year-old woman, Anya Kuznetsova, reports episodes of sudden, intense pain in her hands and feet, 
      which last for hours and are associated with mild swelling. She also complains of fatigue and mild dizziness over the past six months. 
      Her family history is notable for a maternal grandfather with stroke at age 50. On examination, she has bilateral corneal opacities and mild hearing loss. 
      Blood tests reveal elevated lyso-GL-3 levels, and renal ultrasound shows mild cystic changes in both kidneys.
hemophagocytic_lymphohistiocytosis:
  - id: case_1
    text: |
      A 6-year-old boy, Maxim Karpov, presents with persistent fever, rash, and hepatosplenomegaly over the past three weeks. 
      His parents report that his condition has been progressively worsening, and he now appears pale and lethargic. 
      Laboratory tests show a markedly elevated ferritin level (6000 ng/mL), and a high lactate dehydrogenase (LDH). 
      CBC reveals pancytopenia with a low platelet count. An abdominal ultrasound confirms hepatosplenomegaly. 
      His family history is notable for unexplained deaths of two cousins in infancy.
  - id: case_2
    text: |
      A 3-year-old girl, Darya Ivanova, presents with fever, skin rash, and enlarged lymph nodes that have persisted for the past month. 
      Her parents are concerned about weight loss and lethargy. On examination, she appears pale and is febrile at 38.9°C. 
      Laboratory findings include elevated ferritin (4500 ng/mL), elevated liver enzymes, and pancytopenia. 
      A bone marrow biopsy is being performed to confirm the diagnosis of hemophagocytic lymphohistiocytosis. 
      Family history is significant for a brother who died of a similar condition at age 2.
homocystinuria:
  - id: case_1
    text: |
      A 15-year-old boy, Kirill Orlov, presents with a history of developmental delay, mild learning difficulties, 
      and a noticeable increase in height over the past few years. His mother notes that he has been more clumsy and prone to falls. 
      There is no history of vision problems. On examination, he has long limbs, a high-arched palate, and a marfanoid body habitus. 
      His gait is unsteady, and he displays mild hyperflexibility. Blood tests show mild hyperhomocysteinemia, 
      and urine analysis reveals elevated homocystine levels. A genetic test for homocystinuria is pending. 
      Family history is significant for a maternal cousin with intellectual disabilities and a history of blood clots.
  - id: case_2
    text: |
      A 10-year-old girl, Anastasia Pavlova, presents with a history of 
      delayed speech development and frequent episodes of joint dislocation. Her mother is concerned about her vision, as she frequently squints.
      On examination, the child is tall for her age, with a thin build, long fingers, and a high-arched palate. 
      A family history reveals a brother with a history of deep vein thrombosis at a young age. 
      Blood tests reveal elevated homocysteine levels, and a urinalysis shows increased homocystine.
muckle_wells:
  - id: case_1
    text: |
      A 32-year-old woman, Svetlana Ivanova, presents with recurrent episodes of fever, arthralgia, and a maculopapular rash on her forearms. 
      These symptoms have been occurring intermittently for the last 18 months. She also has occasional eye redness and difficulty with joint stiffness in her knees. 
      Family history is notable for a maternal cousin diagnosed with a rare systemic autoinflammatory disorder. 
      On examination, she has a temperature of 38.5°C, a mild rash, and mild swelling in both knees. 
      Laboratory tests show an elevated ESR and CRP.
  - id: case_2
    text: |
      A 28-year-old man, Alexander Zaitsev, presents with recurrent episodes of fever, chills, and pain in his ankles and wrists over the past year.
      These episodes last for several days and are accompanied by a migratory rash on his legs. 
      He reports that these symptoms are most pronounced after stress or infection. 
      His family history reveals a maternal aunt with a history of a similar pattern of recurrent fevers and joint pain, 
      though she was never formally diagnosed. Laboratory investigations show elevated inflammatory markers (CRP, ESR).
paroxysmal_nocturnal_hemoglobinuria:
  - id: case_1
    text: |
      A 25-year-old man, Oleg Melnikov, presents with episodes of dark-colored urine in the morning, 
      particularly after sleep, along with fatigue and pallor. 
      He reports that these episodes have been occurring every few weeks for the past six months. 
      On examination, he is pale but does not have splenomegaly or hepatomegaly. 
      He denies any history of hematuria or significant bleeding. 
      His laboratory results reveal a low hemoglobin level (anemia), elevated reticulocyte count, and low haptoglobin.
  - id: case_2
    text: |
      A 30-year-old woman, Irina Kovalchuk, reports increasing fatigue and intermittent dark urine, 
      which has been especially noticeable upon waking in the morning for the last four months. 
      She has also noticed mild shortness of breath after physical exertion. 
      Family history is notable for a cousin with a history of unexplained anemia. 
      On physical examination, she appears pale and has mild conjunctival pallor. 
      Blood tests show anemia with an elevated LDH and a low platelet count.
prader_willi:
  - id: case_1
    text: |
      A 4-year-old boy, Pavel Sokolov, presents with poor growth, mild developmental delay, 
      and an insatiable appetite over the past year. His parents report that he is constantly hungry 
      and has recently gained weight rapidly despite relatively normal food intake. His motor skills are slightly delayed, 
      and he has mild hypotonia. Family history is negative for genetic disorders. On examination, 
      Pavel is overweight for his age, with a BMI above the 95th percentile, but height is below average.
  - id: case_2
    text: |
      A 3-year-old girl, Elena Fedorova, is brought in by her parents for evaluation of developmental delay and obesity. 
      Elena was born full-term but has been slower than her peers to reach milestones such as walking and talking. 
      Her parents report that she is always hungry, and they are concerned about her increased food-seeking behavior. 
      On physical examination, Elena is overweight, has a short stature, and exhibits mild hypotonia.
primary_biliary_cholangitis:
  - id: case_1
    text: |
      A 40-year-old woman, Maria Golubeva, presents with complaints of fatigue, pruritus, 
      and right upper quadrant discomfort that has been worsening over the past 6 months. 
      She denies jaundice but notes a history of intermittent dark urine and pale stools. 
      Family history is positive for autoimmune thyroid disease in her mother. 
      On physical examination, she has xanthomas on her eyelids and a slightly enlarged liver. 
      Blood tests show elevated alkaline phosphatase and ALT, and a positive anti-mitochondrial antibody (AMA) test.
  - id: case_2
    text: |
      A 45-year-old man, Viktor Ivanov, presents with complaints of increasing fatigue and itchy skin over 
      the past 8 months. He also reports having yellowish eyes. 
      His family history includes a maternal aunt with a history of autoimmune liver disease. 
      On examination, he has scleral icterus and xanthomas on his elbows. 
      Blood tests reveal elevated bilirubin, alkaline phosphatase, and GGT, and a positive AMA test.
undefined:
  - id: case_1
    text: |
        A 19-year-old woman presents with a 4–5 month history of blurred vision, knee pain after walking, and occasional clumsiness. She denies thrombotic events, cognitive delay, or family history of stroke or rare disease. On examination, she is tall and slim with long limbs, showing mild Marfanoid features including arachnodactyly. Ophthalmologic evaluation reveals mild myopia without lens dislocation, and neurologic testing shows slight imbalance on heel-to-toe walk. 
        Skin examination is unremarkable.
        Laboratory studies demonstrate mildly elevated plasma homocysteine (22 µmol/L) with trace urinary homocysteine, while vitamin B6, B12, and folate levels are normal. Plasma methionine was not measured. 
        Coagulation studies, echocardiogram, brain MRI, and slit-lamp examination are all normal. Genetic testing is pending.
        Overall, the patient exhibits Marfanoid features and elevated homocysteine without ectopia lentis, cognitive impairment, or thrombotic history. Genetic confirmation is awaited.