mode: "rag_preparation" # or options: "pre-defined", "generate", "rag_preparation"

diseases:
  - name: "Homocystinuria"
    num_generation: 2
  - name: "Fabry disease"
    num_generation: 2

cases_file: "src/config/generated_cases.yaml"
output_dir: "data/output"

fhir_directory: "data/output/homocystinuria/case_3_f1c1bafe-87bc-40b7-a92a-4bbec701a8ad.json"
parsed_fhir_dir: "data/parsed/"
