
prader-willi_syndrome:
- id: case_1
  text: "A 5-year-old boy, Ethan, presents with concerns from his parents regarding\
    \ his feeding habits and overall development. He is seen for a routine check-up,\
    \ and his vital signs are within normal limits, with a temperature of 36.8 degrees\
    \ Celsius, pulse of 100 beats per minute, blood pressure of 90/60 mmHg, respiratory\
    \ rate of 24 breaths per minute, weight of 18 kilograms, height of 105 centimeters,\
    \ and a body mass index of 16.3. His oxygen saturation is 98% on room air. Ethan's\
    \ parents report that he has been having an increased appetite and has been seeking\
    \ food constantly, which they find challenging to manage. They also mention that\
    \ he has been having some difficulty with speech and gross motor skills, although\
    \ these symptoms are not severe. Laboratory results from a recent blood test show\
    \ a normal complete blood count, basic metabolic panel, and thyroid function tests,\
    \ with the exception of a slightly elevated insulin level of 12 microunits per\
    \ milliliter. Ethan is not currently taking any medications. \n\nEthan's family\
    \ history is notable for his mother having a history of gestational diabetes during\
    \ her pregnancy with him, but both parents are otherwise healthy. There is no\
    \ known family history of genetic disorders or significant medical conditions.\
    \ Ethan's parents have been working with an early intervention program to address\
    \ his developmental delays, and they report that he has been making progress,\
    \ although at a slower pace than his peers. At his previous visit two months ago,\
    \ Ethan's weight was 16 kilograms, and his height was 102 centimeters, indicating\
    \ a steady growth pattern. His parents have also noticed that he has been having\
    \ some difficulties with tantrums and mood swings, particularly when he is denied\
    \ food or does not get his way. Overall, Ethan's presentation is notable for his\
    \ increased appetite and developmental delays, which will require continued monitoring\
    \ and evaluation to determine the underlying cause."
- id: case_2
  text: "A 5-year-old boy, Ethan Thompson, presents with concerns about his appetite\
    \ and eating habits, as reported by his mother. He has been eating more frequently\
    \ and showing interest in food at all times, which is a change from his previous\
    \ eating patterns. His vital signs are within normal limits, with a temperature\
    \ of 36.8 degrees Celsius, pulse of 100 beats per minute, blood pressure of 90/60\
    \ mmHg, respiratory rate of 22 breaths per minute, weight of 21 kilograms, height\
    \ of 110 centimeters, and a body mass index of 17.3. His oxygen saturation is\
    \ 98% on room air. Ethan's mother also mentions that he has been having some difficulty\
    \ with speech and has a tendency to be less active than his peers, although these\
    \ symptoms have been present since early childhood. Laboratory results from a\
    \ recent well-child visit show a hemoglobin level of 13.5 grams per deciliter,\
    \ a hematocrit of 40%, and a platelet count of 250,000 per microliter, all within\
    \ normal ranges for his age. He is not currently taking any medications. \n\n\
    Ethan's family history is notable for his father having a history of obesity,\
    \ which was managed through diet and exercise. Both parents are alive and healthy,\
    \ with no known genetic disorders. Ethan has an older sister who is healthy and\
    \ does not exhibit any similar symptoms. During previous encounters, Ethan's pediatrician\
    \ has noted his slow growth rate and mild delays in achieving certain developmental\
    \ milestones, such as crawling and walking, but these have been attributed to\
    \ individual variation rather than any specific condition. At his last visit two\
    \ months ago, his pediatrician recommended monitoring his eating habits and activity\
    \ level to ensure he maintains a healthy weight and meets his developmental potential."
primary_biliary_cholangitis:
- id: case_1
  text: "A 42-year-old woman, Sarah Thompson, presents with complaints of intermittent\
    \ fatigue and mild itching, particularly on her arms and legs, over the past six\
    \ months. Her vital signs are within normal limits, with a temperature of 36.8\
    \ degrees Celsius, pulse of 72 beats per minute, blood pressure of 120/80 millimeters\
    \ of mercury, respiratory rate of 16 breaths per minute, weight of 65 kilograms,\
    \ height of 160 centimeters, and a body mass index of 25.4. She reports that the\
    \ itching is worse at night and has not noticed any skin lesions or jaundice.\
    \ Laboratory results show a mild elevation in alkaline phosphatase at 140 units\
    \ per liter, with a normal range of 30-120 units per liter, and a slight increase\
    \ in gamma-glutamyl transferase at 55 units per liter, with a normal range of\
    \ 0-50 units per liter. Her complete blood count, electrolyte panel, and liver\
    \ function tests, including aspartate aminotransferase and alanine aminotransferase,\
    \ are within normal limits. She is currently taking a multivitamin daily and has\
    \ been adherent to her medication regimen. \n\nSarah's family history is notable\
    \ for her mother having a history of autoimmune thyroiditis, and both her parents\
    \ are alive and healthy, with no known history of liver disease. She has no previous\
    \ history of liver disease or significant medical conditions. Two months ago,\
    \ she visited her primary care physician for a routine check-up, at which time\
    \ her liver function tests were within normal limits, but she did report some\
    \ fatigue, which was attributed to stress at work at the time. Since then, she\
    \ has noticed the onset of itching and a gradual increase in her fatigue levels.\
    \ She denies any changes in her appetite, bowel movements, or urinary habits and\
    \ has not experienced any abdominal pain or jaundice."
- id: case_2
  text: "A 42-year-old woman, Sarah Thompson, presents with complaints of intermittent\
    \ fatigue and mild itching on her palms and soles over the past six months. She\
    \ reports that these symptoms have been worsening gradually and are more pronounced\
    \ in the evenings. Her vital signs are within normal limits, with a temperature\
    \ of 36.8 degrees Celsius, pulse of 72 beats per minute, blood pressure of 120/80\
    \ millimeters of mercury, respiratory rate of 16 breaths per minute, weight of\
    \ 65 kilograms, height of 160 centimeters, and a body mass index of 25.4. Her\
    \ oxygen saturation is 98% on room air. She denies any fever, abdominal pain,\
    \ or changes in her stool or urine. Laboratory results show a mild elevation in\
    \ alkaline phosphatase at 140 units per liter, with a normal range of 30 to 120\
    \ units per liter, and a gamma-glutamyl transferase of 60 units per liter, which\
    \ is slightly above the normal range of 0 to 55 units per liter. Her complete\
    \ blood count, electrolytes, and liver transaminases are within normal limits.\
    \ She is currently taking a multivitamin once daily and has been adherent to this\
    \ regimen. \n\nSarah's family history is notable for her mother having a history\
    \ of autoimmune thyroiditis, and both parents are alive and healthy, with no known\
    \ history of liver disease. She has no previous history of significant medical\
    \ illnesses and has not had any recent travel or exposure to toxins. Two months\
    \ ago, she had a routine health checkup, which included a normal complete blood\
    \ count and basic metabolic panel. Since then, she reports no significant changes\
    \ in her health except for the progression of her current symptoms. She works\
    \ as an office administrator and has a relatively sedentary lifestyle but denies\
    \ any alcohol or tobacco use."
